// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlq2pPU0OUbH3e5AWGXfFs9UFj5sNY4Ao',
    appId: '1:207963532836:web:9dce33cdfdea8b03ac32b1',
    messagingSenderId: '207963532836',
    projectId: 'pocanalytics-62130',
    authDomain: 'pocanalytics-62130.firebaseapp.com',
    storageBucket: 'pocanalytics-62130.appspot.com',
    measurementId: 'G-QZRQ4S5G82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnieY1NcpINxmLBUUdBriIUurPAgqcWSw',
    appId: '1:207963532836:android:56f0866378ab95b0ac32b1',
    messagingSenderId: '207963532836',
    projectId: 'pocanalytics-62130',
    storageBucket: 'pocanalytics-62130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNNtrQ9sh7QMO1llyonlZ13luR9kjvj8M',
    appId: '1:207963532836:ios:1f0461085b4f959cac32b1',
    messagingSenderId: '207963532836',
    projectId: 'pocanalytics-62130',
    storageBucket: 'pocanalytics-62130.appspot.com',
    iosBundleId: 'com.example.pocFirebaseAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNNtrQ9sh7QMO1llyonlZ13luR9kjvj8M',
    appId: '1:207963532836:ios:77c8ee39f72132d1ac32b1',
    messagingSenderId: '207963532836',
    projectId: 'pocanalytics-62130',
    storageBucket: 'pocanalytics-62130.appspot.com',
    iosBundleId: 'com.example.pocFirebaseAnalytics.RunnerTests',
  );
}
